language: node_js
node_js:
  - 12
before_install:
  - ignore
before_script:
  - ignore

env:
  global:
    - TARGET_JDI_LIGHT_BRANCH="gh-pages"

stages:
  - test
  - lint

jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - echo "Test stage goes here, right now tests are considered passed by default"
        - npm install && npm run build

    - stage: lint
      name: Check for linting errors
      script:
        - npm run lint
after_failure:
  - echo "Build has failed"
after_script:
  - ignore
after_success:
  - echo "Build has succeeded"
