export enum RoutingUrls {
  Badges = 'badges',
  Autocompletes = 'autocompletes',
  Buttons = 'buttons',
  ButtonsToggle = 'buttons_toggle',
  Chips = 'chips',
  Icons = 'icons',
  ProgressBar = 'progress_bar',
  ProgressSpinner = 'progress_spinner',
  Ripple = 'ripple',
  Paginator = 'paginator',
  SortHeader = 'sort_header',
  Tables = 'tables',
  Autocomplete = 'autocomplete',
  Checkbox = 'checkbox',
  Datepicker = 'datepicker',
  FormField = 'form_field',
  Input = 'input',
  RadioButton = 'radio_button',
  Select = 'select',
  SlideToggle = 'slide_toggle',
  Slider = 'slider',
}
