<template>
  <div>
    <v-subheader>Light</v-subheader>
    <v-card
      img="https://cdn.vuetifyjs.com/images/home/vuetify_layout2.svg"
      height="200px"
    >
      <v-system-bar
        color="primary"
        lights-out
        id="system-bar-lights-out-light"
      >
        <v-spacer></v-spacer>
        <v-icon>mdi-wifi-strength-4</v-icon>
        <v-icon>mdi-signal-cellular-outline</v-icon>
        <v-icon>mdi-battery</v-icon>
        <span>12:30</span>
      </v-system-bar>
    </v-card>
    <v-subheader>Dark</v-subheader>
    <v-card
      img="https://cdn.vuetifyjs.com/images/home/vuetify_layout2.svg"
      height="200px"
    >
      <v-system-bar
        color="primary"
        lights-out
        dark
        id="system-bar-lights-out-datk"
      >
        <v-spacer></v-spacer>
        <v-icon>mdi-wifi-strength-4</v-icon>
        <v-icon>mdi-signal-cellular-outline</v-icon>
        <v-icon>mdi-battery</v-icon>
        <span>12:30</span>
      </v-system-bar>
    </v-card>
  </div>
</template>
